spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    username: root
    password: as1212
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/board?serverTimezone=Asia/Seoul


#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      format_sql: true
#      ddl-auto: create
#
#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG
#          type:
#            descriptor:
#              sql:
#                BasicBinder: TRACE