spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    username: root
    password: as1212
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/board?serverTimezone=Asia/Seoul

